@base_url = http://localhost:3000/api/menus

###
// view all menus
GET {{base_url}}/ HTTP/1.1

###
// get menu
GET {{base_url}}/62221399fac3734734039803 HTTP/1.1


###
// create menu
POST {{base_url}}/ HTTP/1.1
Content-Type: application/json

{
  "name": "menu 2",
  "number": 2,
  "image": "this",
  "description": "este es el menu 2",
  "createdDate": "",
  "diners": 4,
  "dishes": ["papas"]
}
