@base_url = http://localhost:3000/api/menus

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RhbGIyQHRlc3QuY29tIiwiaWF0IjoxNjQ2NzUwMTM2LCJleHAiOjE2NDY3NTM3MzZ9.5CtkE9zumk-4dWF8a_E5x6GuXHpIv-AWAVTuNu1TEIo

###
// view all menus
GET {{base_url}}/ HTTP/1.1

###
// get menu
GET {{base_url}}/6224ae1317e143d76a46e6ab HTTP/1.1


###
// create menu
POST {{base_url}}/me HTTP/1.1
Content-Type: application/json
token: {{token}}


{
  "name": "prob menu 5",
  "number": 4,
  "image": "this",
  "description": "prob menu usando ids de productos ",
  "createdDate": "",
  "diners": 4,
  "dishes": ["6220e9bed35877c20787b90f", "6224bc2e1e737c87a92836f4"]
}

###
// add dish to menu
POST {{base_url}}/6224c4180aa1e6ae20de9731 HTTP/1.1
Content-Type: application/json

{
  "productId": "6224bc2e1e737c87a92836f4"
}

###
// update menu
PUT {{base_url}}/6224c4180aa1e6ae20de9731 HTTP/1.1
Content-Type: application/json

{
  "name": "actualizando menu 1",
  "number": 1,
  "image": "this no",
  "description": "este es el menu 1",
  "createdDate": "",
  "diners": 2,
  "dishes": ["tomate"]
}

###
// delete menu
DELETE {{base_url}}/6224ba6d1e737c87a92836f2 HTTP/1.1
