@base_url = http://localhost:3000/api/orders

###
// view all orders
GET {{base_url}}/ HTTP/1.1

###
// get order
GET {{base_url}}/62ad1b3c6db3ec9115a5f712 HTTP/1.1


###
// create order
POST {{base_url}}/ HTTP/1.1
Content-Type: application/json

{
  "clientName": "Pepe5",
  "email": "calvoide@calvo.com",
  "adress": "avenida pepito",
  "phone": "1244211245",
  "purchasedProducts": [
    {
      "product": "6220e9bed35877c20787b90f",
      "quantity": 2
    },
     {
      "product": "6224bc2e1e737c87a92836f4",
      "quantity": 1
    }
  ],
  "purchasedMenus": [],
  "deliveryDate": "12/07/2022"
}

###
// update order
PUT {{base_url}}/62222447fac3734734039804 HTTP/1.1
Content-Type: application/json

{
  "adress" : "actualizando direccion"
}

###
// delete order
DELETE {{base_url}}/6222334c8bdef835a06b3cc0 HTTP/1.1

