@base_url = http://localhost:3000/api/products
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RhbGIyQHRlc3QuY29tIiwiaWQiOiI2MjI3NWM0NDE1YmViNjM3ZDBkYzRiN2UiLCJpYXQiOjE2NDg4MjY1NTAsImV4cCI6MTY0ODgzMDE1MH0.0BEct2nCh_u4xFFTsyzbA7bmFU0d8XABTQIv5p_f_dM

###
// view all products
GET {{base_url}}/ HTTP/1.1

###
// get a product
GET {{base_url}}/6220e9bed35877c20787b90f HTTP/1.1


###
// create a new product
POST {{base_url}}/me HTTP/1.1
Content-Type: application/json
token: {{ token }}

{
  "name": "probando nuevo",
  "image": "esta-de-aqui",
  "description": "probando introduct unidades",
  "ingredients": ["cuscus2", "sal", "perejil"],
  "units": 1,
  "weight": 200
}

###
// update product
PUT {{base_url}}/6220ece2d35877c20787b910 HTTP/1.1
Content-Type: application/json

{
  "name": "ahora soy otro mas",
  "ingredients": ["curcuma", "pollo"]
}

###
// delete product
DELETE {{base_url}}/6224f2071d9218353af79e24 HTTP/1.1
