@base_url = http://localhost:3000/api/products

###
// view all products
GET {{base_url}}/ HTTP/1.1

###
// get a product
GET {{base_url}}/6220e9bed35877c20787b90f HTTP/1.1


###
// create a new product
POST {{base_url}}/ HTTP/1.1
Content-Type: application/json

{
  "name": "cuscus2",
  "image": "esta-de-aqui",
  "description": "cuscus2",
  "ingredients": ["cuscus2", "sal", "perejil"]
}

###
// update product
PUT {{base_url}}/6220ece2d35877c20787b910 HTTP/1.1
Content-Type: application/json

{
  "name": "ahora soy otro mas",
  "ingredients": ["curcuma", "pollo"]
}

###
// delete product
DELETE {{base_url}}/6224f2071d9218353af79e24 HTTP/1.1
