@base_url = http://localhost:3000/api/products
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RhbGIyQHRlc3QuY29tIiwiaWQiOiI2MjI3NWM0NDE1YmViNjM3ZDBkYzRiN2UiLCJpYXQiOjE2NDk2MzEzMTgsImV4cCI6MTY0OTYzNDkxOH0.r2k0aIVKf9nmPxZHqJBE5sqwzPWPs8VzZFxAFuwnjZQ

###
// view all products
GET {{base_url}}/ HTTP/1.1

###
// get a product
GET {{base_url}}/6220e9bed35877c20787b90f HTTP/1.1


###
// create a new product
POST {{base_url}}/me HTTP/1.1
Content-Type: application/json
token: {{ token }}

{
  "name": "probando nuevo",
  "image": "esta-de-aqui",
  "description": "probando introduct unidades",
  "ingredients": ["cuscus2", "sal", "perejil"],
  "units": 1,
  "weight": 200
}

###
// update product
PUT {{base_url}}/me/6250ceb6097761ab988da21d HTTP/1.1
Content-Type: application/json
token: {{ token }}

{
  "ingredients" : "pepe"
}

###
// delete product
DELETE {{base_url}}/me/6250cf49097761ab988da224 HTTP/1.1
token: {{ token }}
